"""create job_postings table

Revision ID: aa2544aab401
Revises: 08e227ccb324
Create Date: 2026-09-10 04:07:03.813021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa2544aab401'
down_revision: Union[str, None] = '08e227ccb324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('nice_to_have_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('min_experience_years', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('junior', 'mid', 'senior', name='job_level'), nullable=False),
    sa.Column('weight_skill_fit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_experience_fit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_values_fit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='job_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings')
    # ### end Alembic commands ###
