"""create email_templates and candidate_emails tables

Revision ID: bfc8831de65e
Revises: 000d5ec2b591
Create Date: 2026-09-12 06:57:33.864705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc8831de65e'
down_revision: Union[str, None] = '000d5ec2b591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('trigger', sa.Enum('shortlisted', 'rejected', 'hired', name='email_trigger'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('trigger')
    )
    op.create_table('candidate_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('sent_by', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.Enum('shortlisted', 'rejected', 'hired', name='email_trigger'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('has_reply', sa.Boolean(), nullable=False),
    sa.Column('reply_snippet', sa.Text(), nullable=True),
    sa.Column('reply_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_emails_candidate_id'), 'candidate_emails', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_emails_candidate_id'), table_name='candidate_emails')
    op.drop_table('candidate_emails')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
