"""create candidate_scores table

Revision ID: c10c7d999bff
Revises: 1801f2cf8c1f
Create Date: 2026-09-10 05:38:20.977751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c10c7d999bff'
down_revision: Union[str, None] = '1801f2cf8c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('skill_fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_fit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('values_fit_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('label', sa.Enum('strong_match', 'consider', 'not_a_fit', name='match_label'), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_scores_candidate_id'), 'candidate_scores', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_scores_candidate_id'), table_name='candidate_scores')
    op.drop_table('candidate_scores')
    # ### end Alembic commands ###
