"""add photo_path to candidates

Revision ID: c1535304030e
Revises: e8065642ac65
Create Date: 2026-09-12 19:24:29.426529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1535304030e'
down_revision: Union[str, None] = 'e8065642ac65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('photo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'photo_path')
    # ### end Alembic commands ###
